### ISSUE TITLE
Kivy installation Instructions

### ISSUE THREAD

**Issue by JustAnother1** [chickenchuck040/octoscreen#1]
The installation instructions linked in the Readme.md do not work on up to date Raspbian or Octopi.

The problem is that the installation needs a certain version of libwayland-dev, libgles2-mesa-dev, libegl1-mesa-dev.

The apt-get install step fails.

**Comment by timothyhollabaugh** [comment]
I'll try installing Kivy on a fresh Raspbian later to see what I can find. Installing Kivy on a Pi has always seemed to be somewhat of a challenge. I'll try to solidify the steps and put them on the README. At some point, you may also need to install mt-dev or mt-devel from apt-get and PIL from pip.

**Comment by timothyhollabaugh** [comment]
@JustAnother1 I created [INSTALL.md](https://github.com/chickenchuck040/octoscreen/blob/master/INSTALL.md) with more detailed installation instructions. They were tested on a Pi 2 with an official display running Raspbian Lite. I did not have any issues with the `apt-get install` for Kivy. Did you `apt-get update` and `apt-get upgrade` first?

**Comment by JustAnother1** [comment]
I worked through the INSTALL.md  on RasPi3 and the official Display. I used Octopi and the oprint folder as env.

The "~/.kivy/config.ini" file was not created. The folder was also not created. Doing nano on the file did not work, as it will not create the folder. Creating the folder solved that and I put the lines in a [input] section.

But at the end it worked! Yeah!

But then I started pressing all kind of buttons. and then it happened(Hope it helps):

pi@octopi:~/octoscreen $ /home/pi/oprint/bin/python2.7 main.py 
[WARNING] [Config      ] Older configuration version detected (0 instead of 16)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_16-12-16_0.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Client      ] Connecting to Octoprint
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [MTD         ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [MTD         ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [MTD         ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO   ] [MTD         ] Read event from </dev/input/event3>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO   ] [HIDInput    ] Read event from </dev/input/event3>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO   ] [HIDInput    ] Read event from </dev/input/event3>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event1> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event3> range position X is 0 - 800
[INFO   ] [MTD         ] </dev/input/event2> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event3> range position Y is 0 - 480
[INFO   ] [MTD         ] </dev/input/event3> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event2> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event3> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event3> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event3> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event1> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event2> rotation set to 0
[INFO   ] [HIDMotionEvent] using < KYE   Optical Mouse>
[INFO   ] [MTD         ] </dev/input/event3> rotation set to 0
[INFO   ] [HIDMotionEvent] using <NOVATEK USB Keyboard>
[INFO   ] [HIDMotionEvent] using <NOVATEK USB Keyboard>
[INFO   ] [HIDMotionEvent] using <FT5406 memory based driver>
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS X position is 0 - 800
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480
[INFO   ] [HIDMotionEvent] using < KYE   Optical Mouse>
[INFO   ] [HIDMotionEvent] using <NOVATEK USB Keyboard>
[INFO   ] [HIDMotionEvent] using <NOVATEK USB Keyboard>
[INFO   ] [HIDMotionEvent] using <FT5406 memory based driver>
[INFO   ] [Client      ] Connecting to Octoprint...
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS X position is 0 - 800
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range ABS Y position is 0 - 480
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position X is 0 - 800
[INFO   ] [HIDMotionEvent] <FT5406 memory based driver> range position Y is 0 - 480
 No handlers could be found for logger "websocket"
[INFO   ] [main.py     ] App.close_settings: <kivy.uix.settings.Settings object at 0x7240d148>
[INFO   ] [Client      ] Connecting to Octoprint
[INFO   ] [Client      ] Connecting to Octoprint...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[WARNING] [Client      ] Could not connect to Octoprint
[WARNING] [Client      ] Trying to reconnect...
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_dbusklipper', 'clipboard_gtk3', 'clipboard_xclip', 'clipboard_xsel'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider.
xclip - OSError: [Errno 2] No such file or directory
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception

xsel - OSError: [Errno 2] No such file or directory
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 15, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception

[INFO   ] [main.py     ] App.close_settings: <kivy.uix.settings.Settings object at 0x7240d148>
[INFO   ] [Client      ] Connecting to Octoprint
[INFO   ] [Client      ] Connecting to Octoprint...
[INFO   ] [main.py     ] App.close_settings: <kivy.uix.settings.Settings object at 0x7240d148>
[INFO   ] [Client      ] Connecting to Octoprint
[INFO   ] [Client      ] Connecting to Octoprint...
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 129, in <module>
     OctoprintLcdApp.run(OctoprintLcdApp())
   File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/base.py", line 500, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 90, in mainloop
     self._mainloop()
   File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 85, in _mainloop
     EventLoop.idle()
   File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/base.py", line 348, in idle
     Builder.sync()
   File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/lang/builder.py", line 691, in sync
     call_fn(next_args[:-1], None, None)
 TypeError: 'NoneType' object has no attribute '__getitem__'
pi@octopi:~/octoscreen $

**Comment by timothyhollabaugh** [comment]
I'm glad you were able to get it to work! As for the config.ini not being created, it must be that it creates that folder and file when you run it the first time, not when it is installed. I will update the installation instructions.

For the crash you got, I think I may have run into that before. It seems to happen occasionally, and I have not found why yet. But I can say that the errors about `xsel` and `xclip` are normal. It is just because the X desktop environment is not installed. I'll try to look into the crash. Did it happen immediately, or after it had been sitting a while?

**Comment by timothyhollabaugh** [comment]
@JustAnother1 I believe I also forgot one line in the config.ini:
Try adding the line
```
keyboard_mode = systemanddock
```
to the `[kivy]` section. That should make a keyboard appear when you try to edit settings.
Let be know if it works and I'll make it set that automatically.

**Comment by JustAnother1** [comment]
I added the line and it did not crash.
As before I see the printer status, the currently loaded file, the print time estimate for it, but nothing else.
I can switch to all the screens. I can get into the settings dialog. If I change things directly in Octpoprint they get updated.
I don't see the available files. I don't see the connection details. And none of the buttons work.

Octoprint is 1.3.0

**Comment by timothyhollabaugh** [comment]
I'll take a look on my test setup. Once I got it all installed and wrote the installation instructions, I did not actually test that it connected to Octoprint. I'll see if I can check that later today.
Make sure that your API key is correct. You can edit it directly in `octoprintlcd.ini` if typing it on the onscreen keyboard get too annoying. The API key is available in the Octoprint settings, then 'API' (if I am remembering correctly).

**Comment by timothyhollabaugh** [comment]
@JustAnother1 I just checked. I believe that your problem is the API key. The default key is the one I use for my printer, but it is different than yours. You will need to change the API key in the Octoscreen settings with the gear icon, or by editing the `octoprintlcd.ini` file in the `octoscreen` directory, to the one that your Octoprint shows in its settings (In the 'API' section).

**Comment by JustAnother1** [comment]
Yes the API Key fixed it. May I recommend that you remove _your_ API Key from the default configuration? Maybee also add something to the Install.md ?

Really cool software! Thank you!

**Comment by timothyhollabaugh** [comment]
After I realized that was the issue, I did remove mine from the config. I also put a nice bold on the [Installation wiki page](https://github.com/chickenchuck040/octoscreen/wiki/Installation).
I am glad that you got it to work! And thanks for helping to iron out bugs in the install process!
