### ISSUE TITLE
New GUI discussion

### ISSUE THREAD

**Issue by marianhlavac** [chickenchuck040/octoscreen#3]
Recently I've had an idea to create a touchscreen interface for OctoPrint to use with 3d printers. Thanks to @chickenchuck040 I've found his project sooner I started trying make own application.

One thing about my idea – the key feature, was having nice looking touch UI attached on printer.

I'd like to participate on this project, helping with development and especially taking charge of creating new GUI for octoscreen.

Let's discuss how octoscreen can look like and let's make some agreement about my improvements on this project.

This is my draft (or mockup, proposal, whatever) how I imagine the Octoscreen could look. I made light and dark variants and we can offer both of them to the users as their choice.

## Light variant

![octoscreen mockup](https://cloud.githubusercontent.com/assets/3010503/21890718/4b00065a-d8cf-11e6-9520-43cba511490c.png)

## Dark variant

![octoscreen mockup dark skin](https://cloud.githubusercontent.com/assets/3010503/21890720/4bfe1574-d8cf-11e6-8264-9fc39891527f.png)

---

**WDYT?**

For better communication - can we reach each other on some kind of IM? 
If not IM, mail is still an option – letters@majko.cz

**Comment by JustAnother1** [comment]
They look good.  But they seem to provide much less informations / Options than the current interface. I also don't see how to switch between them. What should that big play button(Green circle with white triangle) do in the Status Window?

Especially the Home and move axis controls are very helpful for me. I don't see them in your proposal.

I wouldn't want to waste space for up and down arrows for scrolling especially if I can swipe the list in the current version.

I hope this feedback helps. Just my 0.02€

**Comment by marianhlavac** [comment]
@JustAnother1 Well it's incomplete, as you can see, I haven't created some of the screens, this is only to give you an idea how it would look like.

The big play button will probably take you to the 'print from sd card' screen, but I'd like to somehow connect that thing with slic3r, imagine you slice your model, upload it from slic3r to the octoprint, come to printer, clean the bed and just press the big start button :)

I've never said this is complete and final design of all screens. :)

Thanks for feedback. If we're going to create this new GUI (I'm still waiting for @chickenchuck040 's opinion) , I will create an inVision project, where you can pin comments right to the design :)

**Comment by timothyhollabaugh** [comment]
@mmajko That design looks good to me, as long as we keep all the functionality there. 
One important thing is that i want it to be able to nicely adjust to the number of extruders on the printer, as my printer has three.
I was going to start by trying to switch to [KivyMD](https://kivymd.github.io/), as it provides a move modern and clean look.
All the graphics are done with [Kivy](https://kivy.org/#home). The layout itself is designed in Kivy's [kvlang](https://kivy.org/docs/gettingstarted/rules.html), which is kind of like CSS and HTML.
I will busy for the next couple of month with [FIRST Robotics](http://www.firstinspires.org/), and will have little time do do much else.

**Comment by marianhlavac** [comment]
@chickenchuck040 So it would be probably great to get in touch, you will tell me all your requirements and then I can fork repo and get to work, since you're going to be busy, you can just watch and give feedback :)

Should I create another pre-final design (in inVision) for you guys, to give feedback and after agreeing then start working on it? I will include all of the screens there, keeping all functionalities from current version of octoscreen.

**Comment by timothyhollabaugh** [comment]
@mmajko I would be willing to set up a [Discord](https://discordapp.com/) server for Octoscreen for discussions like this. 

It would be good if you created the pre-final design in inVision, and sounds like a good way to move this forward.

**Comment by marianhlavac** [comment]
I use Discord, but i prefer Slack for work-related discussion, I find Discord perfect for gaming and Slack for work. But whatever, I am using both of them, no problem for me.

Alrighty then, I will find myself some time for this.

I think we can close this, as further discussion will be done through IM. Send an invite here and close it :)
